### ISSUE TITLE
query type 65 is invalid

### ISSUE THREAD

**Issue by james-antill** [jvns/dnspeep#7]
Ran it for a while on Mac OS X, get a bunch of:

Error parsing DNS packet: Failed to parse DNS packet: query type 65 is invalid

**Comment by chrismccoy** [comment]
> Ran it for a while on Mac OS X, get a bunch of:
> 
> Error parsing DNS packet: Failed to parse DNS packet: query type 65 is invalid

is this for google/youtube requests? im getting the same with google searches, and youtube video loads

**Comment by nogweii** [comment]
For some context, query type 65 is the 'HTTPSSVC' query ([draft](https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/04/), [upstream github repo](https://github.com/MikeBishop/dns-alt-svc))

**Comment by badnetmask** [comment]
Related: I am getting "query type 256 is invalid" in Linux. I am adding this here, because maybe the code just needs some "consolidated" way to deal with these different/unnusual types of packets.

**Comment by jvns** [comment]
All of the "query type X is invalid" errors are happening because the DNS packet parsing crate `dnspeep` is using is very incomplete and only supports [these record types](https://docs.rs/dns-parser/0.8.0/dns_parser/rdata/enum.RData.html). I think this isn't a great choice of crate and we should use a different one.

Some other Rust DNS code and links to the record types they support right now:

* [dns-message-parser](https://docs.rs/dns-message-parser/0.4.6/dns_message_parser/rr/index.html) (which supports more options and I some didn't see when initially looking for DNS parser crates)
* [trust-dns](https://docs.rs/trust-dns-proto/0.20.1/trust_dns_proto/rr/record_type/enum.RecordType.html#variant.CNAME)
* [dog](https://github.com/ogham/dog/tree/d2d22fd8a4ba79027b5e2013d4ded3743dad5262/dns/src/record)

I think the best thing might to be to use `dns-message-parser` and then make PRs to it to get support for more query types as needed.

**Comment by badnetmask** [comment]
A quick look at dns_message_parser, yes it seems like it does support a lot more types than dns_parser. I can even see type 256 (URI), but not 65 (HTTPS), most likely because that one is still in draft.
Thanks for checking this out!
For me, no rush on the implementation. So far it's been working great for me, the other records are just icing on the cake. :)

**Comment by thomasmerz** [comment]
BTW: On my Linux Client (OpenSUSE) I have seen also some
`Error parsing DNS packet: Failed to parse DNS packet: query type 43 is invalid`
🤔

**Comment by thomasmerz** [comment]
Informational update only ℹ️ 

Message changed with 0.1.2 to:
```
timestamp      query name                           server IP            elapsed   response
Error parsing DNS packet: Failed to parse DNS packet: Could not decode QType: 65
Error parsing DNS packet: Failed to parse DNS packet: Could not decode QType: 65
```

**Comment by jumarko** [comment]
A variant of this issue that shows up on my computer (macOS):
```
Error parsing DNS packet: Failed to parse DNS packet: Could not decode QType: 65

```

**Comment by thomasmerz** [comment]
@jvns , great, thank you very much 🎉 
Can you tell me/us when we will get a new release for this and all other changes since April 2021?

**Comment by jvns** [comment]
Made a new release.

**Comment by jumarko** [comment]
@jvns I've just downloaded the latest version for macos but it still produces this error

```
sudo dnspeep

query name                           server IP            response
Error parsing DNS packet: Failed to parse DNS packet: Could not decode QType: 65
Warning: got response for unknown query ID 11315

```

**Comment by thomasmerz** [comment]
> (This happened when I opened https://curiousprogrammer.net/ in the browser but it might be unrelated)

On my Macbook no error message like this are occuring anymore 👍🏻  Even if I'm opening https://curiousprogrammer.net/ in the browser.

**Comment by thomasmerz** [comment]
But on my Linux Desktop it says that a different type is not yet implemented:
```
Error parsing DNS packet: Failed to parse DNS packet: Decode of type RRSIG is not yet implemented
```
Found an old issue from April 2020 opened by me: https://github.com/jvns/dnspeep/issues/19

**Comment by thomasmerz** [comment]
Opened a new issue for "got response for unknown query ID": https://github.com/jvns/dnspeep/issues/26
